config/routes.rb
Rails.application.routes.draw do
  get "static_pages/index"
  get "static_pages/secret"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html



  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  resources :events
  resources :users
  resources :order, only: [ :new, :create ]

  Rails.application.routes.draw do
    resources :events, only: [ :show ] do
      resources :image, only: [ :create ]
    end
  end

  Rails.application.routes.draw do
    resources :users, only: [ :show ] do
      resources :avatars, only: [ :create ]
    end
  end

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  root to: "events#index"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  after_create :creation_send

  def creation_send
    AttendanceMailer.creation_email(self).deliver_now
  end

  belongs_to :user
  belongs_to :event 
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :administrated_event, class_name: "User"
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def name
    self.first_name + " " + self.last_name
  end
  has_many :attendances
  has_many :events, through: :attendances
  has_many :administrated_event, foreign_key: "administrated_event_id", class_name: "Event"
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name ])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    puts @session

    if @session.payment_intent.present?
      @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
      # @event_id = @session.metadata.event_id
    else
      # Gérez le cas où `payment_intent` est manquant
      flash[:alert] = "Le paiement n'a pas pu être récupéré."
      redirect_to root_path
    end
  end

  def cancel
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    unless current_user
      redirect_to new_user_session_path
    end
  end

  def create
    filterd_params = params.except(:authenticity_token, :commit)
    admin_id = current_user.id
    @event = Event.new(filterd_params.permit(
      :title,
      :description,
      :start_date,
      :duration,
      :location,
      :price
    ))
    @event.image.attach(params[:image])
    @event.id = Event.all.length+1
    @event.administrated_event_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def show
    @event = Event.find params[:id]
    @admin = User.find @event.administrated_event_id
  end
end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.image.attach(params[:image])
    redirect_to(event_path(@event))
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def create
    filtered_params = params.except(:authenticity_token, :total)

    @total = params[:total].to_d
    @event_id = params[:event_id]

    @session = Stripe::Checkout::Session.create(
      payment_method_types: [ "card" ],
      line_items: [
        {
          price_data: {
            currency: "eur",
            unit_amount: (@total*100).to_i,
            product_data: {
              name: "Rails Stripe Checkout"
            }
          },
          quantity: 1
        },
        metadata: {
        # event_id: @event_id
      }

      ],
      mode: "payment",

      success_url: checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url: checkout_cancel_url
    )

    redirect_to @session.url, allow_other_host: true
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/eventimage_helper.rb
module EventimageHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/cancel.html.erb
 <div class="container text-center my-5"> <h1>Echec</h1> <p>Le paiement n'a pas abouti.</p> </div>

app/views/checkout/success.html.erb
<div class="container text-center my-5"> <h1>Succès</h1> <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p> <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> </div>

app/views/events/index.html.erb
<div class="centered-container">

  <h1 class="pixel">Eventbite</h1>

<% @events.each do |event| %>

<div class="event-card">
  <p> <%= event.title %> </p>
  <p> Commence le: <%= event.start_date.strftime("%d/%m/%Y") %> </p>
  <%= link_to "Voir l'évenement", event_path(event.id)%>
</div>

<% end %>

</div>

app/views/events/new.html.erb
<div class="centered-container">
  <h1 class="pixel">Créer un nouvel event</h1>
  <div class="event-card ">
<%= form_tag events_path(action: 'create'),  method: "post" do %>
<div class="form-field">
  <%= label_tag :titre %>
  <%= text_field_tag :title%>
</div>

<div class="form-field">
  <%= label_tag :description %>
  <%= text_area_tag :description%>
</div>

<div class="form-field">
  <%= label_tag :date %>
  <%= date_field_tag :start_date%>
</div>

<div class="form-field">
  <%= label_tag :durée %>
  <%= select_tag :duration, options_for_select(1..24)%>
</div>

<div class="form-field">
  <%= label_tag :localisation %>
  <%= text_field_tag :location%>
</div>

<div class="form-field">
  <%= label_tag :prix %>
  <%= text_field_tag :price%>
</div>

<div class="form-field">
  <%= submit_tag 'Valider' %>
<div>

  
<%end%>
</div>
</div>

app/views/events/show.html.erb
<div class=centered-container>

<h1 class="pixel"> <%= @event.title %> </h1>


<div class="event-card">
<p> <%= @event.description %> </p>

<p> Par <%= @admin.email %> </p>

<p> Débute le  <%= @event.start_date.strftime("%d/%m/%Y") %> </p>

<p> Dure  <%= @event.duration %> </p>

<p> Prix  <%= @event.price %> €</p>

<%if @event.image.attached?%>
  <%= image_tag @event.image, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas d'image liée à cet évenement ===</p>
<%end%>
</div>

<%if current_user && current_user.id == @admin.id%>
<h3>Changer l'image ?</h3>
<%= form_tag event_image_index_path(@event), multipart: true do %>
  <%= file_field_tag :image %>
  <%= submit_tag "Mettre à jour" %>
<% end %>
<%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Eventbrite" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <script src="https://js.stripe.com/v3/"></script>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
      
      <%= link_to "Accueil", events_path, class: "navbar-brand" %>   
      
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
  <% if user_signed_in? %>

      <li class="nav-item dropdown ml-auto">
    <a class="nav-link dropdown-toggle mr-10" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Mon profil
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
      
      
      <%= link_to current_user.email , user_path(current_user.id)%> 
    
    </div>
    </li>

  <% else %>
  <li class="nav-item dropdown ml-auto">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Compte
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">

      <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
      
      <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
    
    </div>
  
  </li>
  
  

  <% end %>
  
    <%= link_to "Créer un nouvel event", new_event_path, class: "nav-link" %>
  </div>
  
</nav>
    <%= yield %>
  </body>
</html>

app/views/order/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/order/new.html.erb
<%= button_to "Passer commande (NEXT GEN)", order_index_path(total: 50), class: "btn btn-primary", remote: true %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    
  </body>
</html>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<p>page de profil de l'utilisateur <%= @user.first_name %></p>

<% if @user.avatar.attached? %>
    <%= image_tag @user.avatar, alt: 'avatar' %>
<% end %>

<h3>Changer d'avatar ?</h3>
<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>